# Generated by Selenium IDE
from Imports_Packages import *
# import time
# import json
# from selenium import webdriver
# from selenium.webdriver.common.by import By
# from selenium.webdriver.common.action_chains import ActionChains
# from selenium.webdriver.support import expected_conditions
# from selenium.webdriver.support.wait import WebDriverWait
# from selenium.webdriver.common.keys import Keys
# from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestOlx():
  # def __init__(self,data):

  def setup_method(self,):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, ):
    self.driver.quit()

  def click_element_until_hidden_or_disabled(self,CSS_selector, timeout=60, sleep_interval=1):
    start_time = time.time()
    while time.time() - start_time < timeout:
      try:
        element = WebDriverWait(self.driver, 20).until(
          EC.element_to_be_clickable((By.CSS_SELECTOR, CSS_selector))
        )
        element.click()
      except TimeoutException:
        # Handle timeout (element not found, disabled, or hidden)
        break
      except Exception as e:
        # Handle other exceptions if necessary
        print(f"An error occurred: {e}")
        break
      time.sleep(sleep_interval)

  def test_olx(self):
    # Test name: olx
    # Step # | name | target | value
    # 1 | open | https://www.olx.com.pk/ | 
    self.driver.get("https://www.olx.com.pk/")
    # 2 | setWindowSize | 1240x703 | 
    self.driver.set_window_size(1240, 703)
    # 3 | click | css=.\_162767a9:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\_162767a9:nth-child(1)").click()
    # 4 | type | css=.\_162767a9:nth-child(1) | ipad mini 6
    self.driver.find_element(By.CSS_SELECTOR, ".\\_162767a9:nth-child(1)").send_keys("ipad mini 6")
    # 5 | sendKeys | css=.\_162767a9:nth-child(1) | ${KEY_ENTER}
    self.driver.find_element(By.CSS_SELECTOR, ".\\_162767a9:nth-child(1)").send_keys(Keys.ENTER)
    # 6 | click | css=.\_95dae89d > .\_4408f4a8 |

    self.click_element_until_hidden_or_disabled(".\\_4408f4a8 > .\\_5079de6b:nth-child(1)")
    # 7 | runScript | window.scrollTo(0,4517.14990234375) | 
    self.driver.execute_script("window.scrollTo(0,4517.14990234375)")
    # 8 | click | css=.\_4408f4a8 > .\_5079de6b:nth-child(1) |
    self.driver.close()
  
testolx = TestOlx()
testolx.setup_method()
testolx.test_olx()
