# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestOlx():
    def setup_method(self, ):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, ):
        self.driver.quit()

    def test_olx(self):
        self.driver.get("https://www.olx.com.pk/")
        self.driver.set_window_size(1240, 703)
        self.driver.find_element(By.CSS_SELECTOR, ".\\_162767a9:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".\\_162767a9:nth-child(1)").send_keys("ipad mini 6")
        self.driver.find_element(By.CSS_SELECTOR, ".\\_162767a9:nth-child(1)").send_keys(Keys.ENTER)
        self.driver.find_element(By.CSS_SELECTOR, ".\\_162767a9:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".\\_4b2c6986:nth-child(6) .\\_6d5b4928").click()


testolx = TestOlx()
testolx.setup_method()
testolx.test_olx()
# testolx.teardown_method()

